#!/bin/sh
addgroup --system thicc-rest 2> /dev/null > /dev/null ; true
adduser --system thicc-rest --home /etc/thicc --ingroup thicc-rest 2> /dev/null > /dev/null ; true
chmod 700 /etc/thicc/keys
deb-systemd-helper enable thicc.service
